version: "3.8"

networks:
  artist-management-system:
    driver: bridge

services:
  db:
    image: mysql:latest
    container_name: artist-management-system_db
    cap_add:
      - SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      MYSQL_DATABASE: artist-management-system
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./server/db-data:/var/lib/mysql
    ports:
      - 4306:3306
    networks:
      - artist-management-system
  
  api:
    build:
      context: ./server/
      dockerfile: Dockerfile
    image: api_image
    container_name: artist-management-system_api
    depends_on:
      - db
    user: 1000:1000
    working_dir: /home/artist-management-system
    ports:
      - 8848:8848
    volumes:
      - ./server:/home/artist-management-system
    networks:
      - artist-management-system
  
  client:
    build:
      context: ./client/
      dockerfile: Dockerfile
    image: client_image
    container_name: artist-management-system_client
    depends_on:
      - api
    user: 1000:1000
    working_dir: /home/artist-management-system
    ports:
      - 3000:3000
    volumes:
      - ./client:/home/artist-management-system
    networks:
      - artist-management-system
