# Base image
FROM node:lts-alpine

# Setup working directory in the container fs
WORKDIR /home/artist-management-system

# Copy the package dependencies
COPY ../server/package.json ../server/yarn.lock ./

# Install dependencies
RUN yarn

# Copy the contents of current host dir to container working dir
COPY ../server ./

# Expose port for mapping
EXPOSE 8848

# Command to start the app
CMD ["yarn", "start:dev"]
