# Base image
FROM node:lts-alpine

# Setup working directory in the container fs
WORKDIR /home/artist-management-system

# Copy the package dependencies
COPY ../client/package.json ../client/yarn.lock

# Install dependencies
RUN yarn

# Copy the contents of current host dir to container working dir
COPY ../client .

# Expose port for mapping
EXPOSE 3000

# Command to start the app
CMD ["yarn", "start"]
